[package]
name = "numeric_cast"
version = "0.2.1"
edition = "2021"
description = "safely cast between numbers"
keywords = ["cast"]
categories = ["rust-patterns", "no-std"]
rust-version = "1.56.0"
license.workspace = true
repository.workspace = true
