[package]
name = "nugine-rust-utils"
version = "0.1.1"
edition = "2021"
description = "Nugine's personal Rust utilities"
license = "MIT"

[lib]
name = "rust_utils"

[features]
default = []
std = ["alloc"]
alloc = []
