on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    - cron: '0 0 * * 0' # at midnight of each sunday
  workflow_dispatch:

name: CI

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy, miri
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: just test
      - run: just miri

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - uses: dtolnay/rust-toolchain@stable
      - run: just test
      - uses: dtolnay/rust-toolchain@1.65.0
      - run: just test
